In [2]:
import pickle
with open('/content/markpredictionmodel','rb') as s:
  reg=pickle.load(s)

In [3]:
import pandas as pd
df=pd.read_csv('/content/marks_input - Sheet1.csv')
df

    cia1  cia2  cia3
0     60    55    65
1     50    45    38
2     60    85    34
3     78    64    72
4     82    94    76
5     66    73    85
6     56    62    46
7     78    78    76
8     70    82    66
9     30    28    28
10    67    45    94
11    75    92    72
12    66    82    37
13    67    42    58
14    80    51    62
15    70    66    74
16    50    73    92
17    82    75    81
18    64    35    65
19    70    55    71

In [7]:
final_mark=reg.predict(df)
final_mark

array([63.3361689 , 49.14873368, 62.20993766, 74.33736963, 84.90017928,
       76.13211874, 58.17361005, 79.20814399, 74.4210088 , 34.42485212,
       71.723654  , 80.64517206, 64.48529428, 60.41043361, 68.70834149,
       72.52804573, 72.33245124, 81.33729087, 59.50905819, 68.7427546 ])

In [8]:
df['finalmarks']=final_mark
df

    cia1  cia2  cia3  finalmarks
0     60    55    65   63.336169
1     50    45    38   49.148734
2     60    85    34   62.209938
3     78    64    72   74.337370
4     82    94    76   84.900179
5     66    73    85   76.132119
6     56    62    46   58.173610
7     78    78    76   79.208144
8     70    82    66   74.421009
9     30    28    28   34.424852
10    67    45    94   71.723654
11    75    92    72   80.645172
12    66    82    37   64.485294
13    67    42    58   60.410434
14    80    51    62   68.708341
15    70    66    74   72.528046
16    50    73    92   72.332451
17    82    75    81   81.337291
18    64    35    65   59.509058
19    70    55    71   68.742755

In [9]:
df.to_csv('marksprediction_clientOP.csv',index=False)

In [12]:
import warnings
warnings.filterwarnings('ignore')
import math
m1=int(input("enter CIA 1 mark:"))
m2=int(input("enter CIA 2 mark:"))
m3=int(input("enter CIA 3 mark:"))
fin=reg.predict([[m1,m2,m3]])
final=math.floor(fin)
print("the Expected final mark is:",final)

enter CIA 1 mark:39
enter CIA 2 mark:59
enter CIA 3 mark:78
the Expected final mark is: 60